### ISSUE TITLE
balloon height -- limited functionality and documentation

### ISSUE THREAD

**Issue by tonyc10** [skydoves/Balloon#34]
**Please complete the following information:**
- Library Version: 1.1.2
- Affected Device(s) emulator
 
**Describe the Bug:**

Apart from `setHeight()`, there does not seem to be any control over height.  The balloon does not seem to properly wrap my content -- whether I use just text or set my own custom layout.  
  
I do not see much documentation concerning height.  

Do I need to guess the proper height and then set it using `setHeight()` anytime I have more than one line of text?

**Expected Behavior:**

If I do not set height manually, e.g. `setHeight()`, I am hoping the balloon will wrap the content, setting the correct height for me.  Otherwise, even if I calculate and set a correct height for each of my balloons, it will still be wrong whenever the user has a different font display size than what I am expecting, or a different language.

**Comment by skydoves** [comment]
@tonyc10 
Hi, thank you for your issue :)
It is resolved on the new version [1.1.5](https://github.com/skydoves/Balloon/releases/tag/1.1.5).

**Comment by robertodries92** [comment]
I'm still experiencing this issue with a custom layout on 1.1.5

**Comment by skydoves** [comment]
It seems related to #42

**Comment by dvasundhara** [comment]
if my icon moves on the toolbar , the arrow do not point to correct icon. For ex: if chrome cast icon added or removed , it shifts my image on the toolbar. the arrow does not follow the image position.
