### ISSUE TITLE
Text/images cut off on sides

### ISSUE THREAD

**Issue by gavingt** [skydoves/Balloon#42]
If the width of the Balloon is close to the width of the content inside it, the content gets cut off on the left and right sides.

I've tried playing with various builder methods to fix this, and nothing does.

![Screenshot_1587902594](https://user-images.githubusercontent.com/24281417/80307006-672dbf80-877b-11ea-8fed-5d276b8841c2.png)

**Comment by skydoves** [comment]
Hi, @gavingt could you let me know about your device information?

**Comment by gavingt** [comment]
It's happening on all devices. The above screenshot is from a Nexus S API 28 emulator.

Here's my physical Pixel 3 on API 29:

![Screenshot_20200426-061555](https://user-images.githubusercontent.com/24281417/80308826-fd66e300-8785-11ea-8a7d-9686e1739dec.png)

And here's another emulator (Nexus 5X API 26):

![Screenshot_1587907158](https://user-images.githubusercontent.com/24281417/80308845-1374a380-8786-11ea-9133-03b8d255572f.png)

All I'm doing is changing the text string in the sample app. Once it reaches a certain length, the text and icon get cut off.

**Comment by skydoves** [comment]
Hmm. I built using Nexus 5X API 26, Gallaxy s7/10 but it works fine.
I will check its details more.

![screenshot389987803](https://user-images.githubusercontent.com/24237865/80309196-6b56ed00-880e-11ea-998c-45e8bd999221.png)

**Comment by gavingt** [comment]
If the text is long enough, it will wrap around to the next line and nothing will be cut off. But if it's just the right length, it will get cut off. 

In other words, if the string just barely fits in one line, it'll be cut off.

**Comment by NikoBoerger** [comment]
Just ran into the same issue. Glad someone reported it already. Will it come in version 1.1.7? Thank you!

**Comment by skydoves** [comment]
Hi, this issue will be resolved in the next version.
Thank you :)

**Comment by skydoves** [comment]
Hi, @gavingt , @NikoBoerger 
It is fixed on the new version [1.1.7](https://github.com/skydoves/Balloon/releases/tag/1.1.7).
Thank you for your issue :)

**Comment by NikoBoerger** [comment]
Hi @skydoves,
thank you so much for the fix. It works great on most of my devices. However, on my Samsung Tablet I still experience the Icon being cut at the left side, and the text being cut on the right side with the version 1.1.7. Exactly like on the initial screenshot from gavingt.

This is my setting:

```    
public static Balloon.Builder createBalloonBuilder(View view, Activity activity) {
        return new Balloon.Builder(activity)
                .setArrowSize((int) toDp(R.dimen._10sdp, activity))
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowVisible(true)
                .setArrowPosition(calculateArrowPosition(view, activity))
                .setWidthRatio(1.0f)
                .setPaddingTop((int) toDp(R.dimen._10sdp, activity))
                .setPaddingBottom((int) toDp(R.dimen._10sdp, activity))
                .setTextSize(toDp(R.dimen._12sdp, activity))
                .setCornerRadius(toDp(R.dimen._4sdp, activity))
                .setAlpha(0.95f)
                .setIconSize((int) toDp(R.dimen._20sdp, activity))
                .setPaddingLeft((int) toDp(R.dimen._10sdp, activity))
                .setPaddingRight((int) toDp(R.dimen._10sdp, activity))
                .setTextColor(ContextCompat.getColor(activity, R.color.colorPrimaryDark))
                .setBackgroundColor(ContextCompat.getColor(activity, R.color.colorPrimary100))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setDismissWhenTouchOutside(true)
                .setDismissWhenClicked(true);
    } 
```

![Screenshot_20200517-173838_Dart Pro Training Sheet](https://user-images.githubusercontent.com/8778527/82153080-a1175080-9865-11ea-92b7-f8efa3343c75.jpg)

**Comment by gavingt** [comment]
Thanks for your hard work. But I'm noticing after the 1.17 update that the width of the Balloon no longer shrinks to fit the text when a specific width or width ratio is not set.

**Comment by skydoves** [comment]
Hi, @NikoBoerger 
I just re-published the `1.1.7` version.
Please run below command and rebuild your project.
```
./gradlew build --refresh-dependencies
```

**Comment by gavingt** [comment]
This seems solved to me. I'm not getting text or icons cut off on any of my devices. Thank you so much!

**Comment by NikoBoerger** [comment]
Even when clearing all of my gradle caches and using --refresh-dependencies, gradle is still downloading the old 1.1.7 version. Are you sure the new 1.1.7 is released on jitpack? It seems like it worked for gavingt though, but I don't have any more ideas.
