### ISSUE TITLE
BalloonFactory cannot be instantiated using gradle 8.1 and proguard

### ISSUE THREAD

**Issue by zenyagami** [skydoves/Balloon#487]
**Please complete the following information:**
- Library Version 1.5.4
- Affected Device(s) Pixel 7 Pro Android 14 ,
**Describe the Bug:**
I migrated to gradle 8.1  (it was working correctly in 7.4), however now when I use proguard (in debug seems to work fine) i receive the followin error
` java.lang.Class<com.class.compose.tooltip.BalloonFactory$SwipeToDeleteBalloon> cannot be instantiated`
this is my SwipeToDeleteBalloon code
```kotlin
 class SwipeToDeleteBalloon : Balloon.Factory() {
        override fun create(context: Context, lifecycle: LifecycleOwner?): Balloon {
            return createBalloon(context) {
                setArrowSize(11)
                setArrowOrientationRules(ArrowOrientationRules.ALIGN_ANCHOR)
                setArrowOrientation(ArrowOrientation.TOP)
                setArrowPosition(0.85f)
                setWidth(BalloonSizeSpec.WRAP)
                setHeight(90)
                setPaddingLeft(16)
                setPaddingRight(16)
                setCornerRadius(4f)
                setTextSize(16f)
                setIconForm(iconForm(context) {
                    drawable = ContextCompat.getDrawable(context, R.drawable.ic_delete_outline_24)
                    iconColor = MaterialColors.getColor(context, com.google.android.material.R.attr.colorOnPrimaryContainer, "")
                    setIconSize(context.resources.getDimensionPixelOffset(R.dimen.status_bar_size_extra))
                })
                setTextColor(MaterialColors.getColor(context, com.google.android.material.R.attr.colorOnPrimaryContainer, ""))
                setText(context.getString(R.string.tool_tip_swipe_to_delete_app))
                setBackgroundColor(context.getPrimaryContainerColor())
                setBalloonAnimation(BalloonAnimation.CIRCULAR)
                setLifecycleOwner(lifecycle)
                setPreferenceName(PREFERENCE_NAME_BALLOON_SWIPE)
                setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
                setShowCounts(3)
            }
        }
    }
```

**Expected Behavior:**
The app should not crash
stacktrace
```
Fatal Exception: java.lang.InstantiationException: java.lang.Class<com.class.compose.tooltip.BalloonFactory$SwipeToDeleteBalloon> cannot be instantiated
       at java.lang.Class.newInstance(Class.java)
       at com.skydoves.balloon.internals.ActivityBalloonLazy.getValue(ActivityBalloonLazy.kt:47)
       at com.skydoves.balloon.internals.ActivityBalloonLazy.getValue(ActivityBalloonLazy.kt:34)
       at app.ui.main.preferences.SortLauncherAppsActivity.getSwipeToDeleteBalloon(SortLauncherAppsActivity.kt:42)
       at app.ui.main.preferences.SortLauncherAppsActivity.displayToolTip(SortLauncherAppsActivity.kt:157)
       at app.ui.main.preferences.SortLauncherAppsActivity.setItemsData(SortLauncherAppsActivity.kt:152)
       at app.ui.main.preferences.SortLauncherAppsActivity.access$displayShortcutChooser(SortLauncherAppsActivity.kt:37)
       at app.ui.main.preferences.SortLauncherAppsActivity.access$setItemsData(SortLauncherAppsActivity.kt:37)
       at app.ui.main.preferences.SortLauncherAppsActivity$onCreate$2$1.invokeSuspend(SortLauncherAppsActivity.kt:75)
       at app.ui.main.preferences.SortLauncherAppsActivity$onCreate$2$1.invoke(SortLauncherAppsActivity.kt:2)
       at app.ui.main.preferences.SortLauncherAppsActivity$onCreate$2$1.invoke(SortLauncherAppsActivity.kt:1)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:2)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:1)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:2)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:1)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:1)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith$kotlinx_coroutines_core(DispatchedContinuation.java:256)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
       at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
       at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
       at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1689)
       at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:642)
       at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
       at kotlinx.coroutines.channels.BufferedChannel.access$onClosedReceiveCatchingOnNoWaiterSuspend(BufferedChannel.kt:36)
       at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
       at kotlinx.coroutines.channels.BufferedChannel.sendImpl$default(BufferedChannel.kt:304)
       at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:113)
       at kotlinx.coroutines.channels.BufferedChannel.send(BufferedChannel.kt)
       at kotlinx.coroutines.channels.ChannelCoroutine.send(ChannelCoroutine.kt:2)
       at androidx.lifecycle.FlowExtKt$flowWithLifecycle$1$1$1.emit(FlowExt.kt:93)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
I will try to remove `com.google.android.material.R.attr.colorOnPrimaryContainer` but I need to do some tests
but this is only happening with proguard r8 full 
EDIT: I just checked and seems that is the same in all Android versions I removed colors like `com.google.android.material.R.attr.colorOnPrimaryContainer` and still the crash is there.

**Comment by zenyagami** [comment]
After some research if i turn on "compability" mode, seems that is working, doing this in `gradle.properties`
android.enableR8.fullMode=false
also I tried ` Balloon.Factory()`with only one setter and is still crashing. so I'm not sure if I should do something with  R8 Full mode.

**Comment by rahulshah0891** [comment]
Facing same issue when switching to AGP 8.0.

**Comment by rahulshah0891** [comment]
Resolved this crash by creating Balloon object like this:

`CustomViewBalloonFactory().create(requireContext(), viewLifecycleOwner)`

and removing:

`private val customBalloon by balloon<CustomViewBalloonFactory>()
`

**Comment by skydoves** [comment]
Hey @zenyagami @rahulshah0891  guys, sorry for the very delayed response.

A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by zenyagami** [comment]
@skydoves I tried with the latest version, and I still have the same issue, but differnt stacktrace
NoSuchMethodException:
```
java.lang.NoSuchMethodException: com.test.ui.compose.tooltip.BalloonFactory$SwipeToDeleteBalloon.<init> []
       at java.lang.Class.getConstructor0(Class.java:3325)
       at java.lang.Class.getDeclaredConstructor(Class.java:3063)
       at com.skydoves.balloon.internals.ActivityBalloonLazy.getValue(ActivityBalloonLazy.kt:47)
       at com.skydoves.balloon.internals.ActivityBalloonLazy.getValue(ActivityBalloonLazy.kt:34)
```

**Comment by skydoves** [comment]
Hmm, I suspect the lifecycle version might be colliding. Which lifecycle version do you use? Balloon uses `androidx.lifecycle:lifecycle-runtime-ktx:2.6.2`.

**Comment by skydoves** [comment]
Hey guys, I'm closing this issue now. If you still face the same issue, please let me know! Thanks!

**Comment by akamahesh** [comment]
facing this issue... on release build 
versions that i am using 

```
const val androidxLifecyle = "2.7.0"
const val ftueTooltip = "1.6.4"
```

**Comment by akamahesh** [comment]
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.7.0

found this on release note of lifecycle lib,
please have a look if it helps

`The proguard keep rules associated with LifecycleObserver have been removed. This means that proguarded code that wishes to use APIs via reflection (such as using the long since deprecated @OnLifecycleEvent annotation) will need to provide their own keep rules for their specific use case.`

**Comment by akamahesh** [comment]
FYI: i have fixed it by adding all my Factory class in proguard 

-keep class com.example.libraries.ftuelib.ui.factory.** { *; }
